Default: &defaults
  database: IOU.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: IOU_test.sqlite3
  <<: *defaults

Staging:
  database: IOU_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: IOU_production.sqlite3
  poolsize: 100
  <<: *defaults
